spring:
  data:
    mongodb:
      username: ahmed
      password: ahmed
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090